### ISSUE TITLE
Remove top right border radius

### ISSUE THREAD

**Issue by danleyb2** [danleyb2/hlp#1]
- [x] Element2
- [x] Element3
- [x] Element4

## They currently look like this 
![2020-08-11_19-59](https://user-images.githubusercontent.com/9919961/89926171-2748f600-dc0d-11ea-90f3-c09fd60c7966.png)

## Please refer to the original image below 
![2020-08-11_11-01_1](https://user-images.githubusercontent.com/9919961/89926071-0385b000-dc0d-11ea-86de-089343f60032.png)

**Comment by alovega** [comment]
reflected on latest pull request
