### ISSUE TITLE
Center Element 3 main content

### ISSUE THREAD

**Issue by danleyb2** [danleyb2/hlp#2]
## It currently look like this 
![2020-08-11_20-01](https://user-images.githubusercontent.com/9919961/89926347-6b3bfb00-dc0d-11ea-982f-a8114fe16a0a.png)

## Please refer to the original image below 
![2020-08-11_11-01_1](https://user-images.githubusercontent.com/9919961/89926071-0385b000-dc0d-11ea-86de-089343f60032.png)

**Comment by alovega** [comment]
reflected on latest pull request
